language: c
compiler:
  - gcc
  - clang
before_script: 
- sudo apt-get update -qq
- sudo apt-get install -qq gfortran 
- sudo apt-get install -qq  gcc-multilib gfortran-multilib
- sudo apt-get install -qq liblapack-dev
script: curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-all | bash 
after_script: luajit -ltorch -e "torch.test()"
